sudo: required
services:
  - docker

before_instal:
  - docker build -t msunova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true msunova/docker-react npm run test --coverage


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-659813118302"
  bucket_path: "Docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"