# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: Docker@2
      displayName: Build an image
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MarSu Azure 1(6ceaca88-4f57-4ade-82c0-ee2aa69dc913)'
    subscriptionId: '6ceaca88-4f57-4ade-82c0-ee2aa69dc913'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'marsu-ba-test001'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
